name: Build and Unit Test

on:
  pull_request:
    branches:
      - main  # Specify the branch your PRs target

jobs:
  build_and_run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: npm run test
